version: "3.6"

services:
  nodered:
    image: nodered/node-red
    ports:
    - 1880:1880
    volumes:
    - node_red_data:/data
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - mosquitto-conf:/mosquitto/config
    restart: unless-stopped
  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_DB: db
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: secret
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: secret
    volumes: 
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086 
    restart: unless-stopped  

volumes:
  node_red_data:
  grafana:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
  influxdb:
